[package]
name = "proto-build"
version = "0.1.0"
authors = ["Sergei Sotnikov <ssotnikov93@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
prost = "0.12"
prost-build = "0.12"
tonic = "0.10"
tonic-build = "0.10"
regex = "1"
walkdir = "2"
